### ISSUE TITLE
Captcha is required

### ISSUE THREAD

**Issue by vovanduc** [notfoundsam/yahoo-auction#22]
Hi Alexey,

I have error when run project:

bool(false) Captcha is required AgAAAIkBAAABAAAAAAAAAAABAY8XRIE https://ncaptcha.yahoo.co.jp/v1/img/AgAAAIkBAAABAAAAAAAAAAABAY8XRIE

Thanks

**Comment by notfoundsam** [comment]
@vovanduc Sorry for late answer. Is it actual yet?

**Comment by notfoundsam** [comment]
If you got this error it means you did too many login requests to Yahoo. Wait for an hour and try again. Is it still required a captcha, try to log in to Yahoo through a normal browser with your credentials. Enter a captcha code and try again through the library.

**Comment by notfoundsam** [comment]
Closed
